Added additional configuration options for numberSlider per issue #1720
eirannejad/pyRevit pull request #1728
Opened 2023-02-09 15:24 UTC by alexdaversa

PR to resolve issue #1720

2023-03-17 18:20 UTC, thumDer requested changes

2023-03-17 18:20 UTC, thumDer commented on pyrevitlib/pyrevit/forms/__init__.py
> +def ask_for_number_slider(default=None, min=0, max=100, interval=1 prompt=None, title=None, **kwargs):
a comma is missing before `prompt`

2023-03-17 18:20 UTC, thumDer commented on pyrevitlib/pyrevit/forms/__init__.py
>      This is a shortcut function that configures :obj:`GetValueWindow` for
Please extend the docstring as well

2023-03-17 19:20 UTC, alexdaversa commented on pyrevitlib/pyrevit/forms/__init__.py
> +def ask_for_number_slider(default=None, min=0, max=100, interval=1 prompt=None, title=None, **kwargs):
@thumDer thanks! will update PR

2023-03-17 19:29 UTC, alexdaversa commented on pyrevitlib/pyrevit/forms/__init__.py
>      This is a shortcut function that configures :obj:`GetValueWindow` for
@thumDer thanks! I extended docstring as well.

2023-03-24 15:44 UTC, merged

2023-03-24 15:45 UTC, jmcouffin commented
Well done, @alexdaversa thanks